# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: cargo-fmt-sdk
        name: cargo fmt (sdk)
        entry: cargo fmt --manifest-path solana-indexer-sdk/Cargo.toml --
        language: system
        types: [rust]
        pass_filenames: false
      - id: cargo-fmt-benches
        name: cargo fmt (benches)
        entry: cargo fmt --manifest-path benches/Cargo.toml --
        language: system
        types: [rust]
        pass_filenames: false
      - id: cargo-fmt-examples
        name: cargo fmt (examples)
        entry: cargo fmt --manifest-path examples/Cargo.toml --
        language: system
        types: [rust]
        pass_filenames: false
      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy
        language: system
        pass_filenames: false
        types: [rust]
        # Always pass --all-targets to clippy to lint all code, including tests and benches
        args: ["--all-targets", "--", "-D", "warnings"]